import fs from 'node:fs';
import path from 'node:path';

const [inputPath, outputPath] = process.argv.slice(2);

if (!inputPath || !outputPath) {
  throw new Error('Usage: node scripts/generate_website_manifest.mjs INPUT OUTPUT');
}

const input = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
const periods = ['daily', 'weekly', 'monthly'];

if (!Array.isArray(input.languages) || input.languages.length === 0) {
  throw new Error('The feed manifest must contain at least one language.');
}

const slugs = new Set();
for (const language of input.languages) {
  if (!language || typeof language.displayName !== 'string' || language.displayName.length === 0) {
    throw new Error('Every feed language must have a displayName.');
  }
  if (typeof language.slug !== 'string' || language.slug.length === 0 || slugs.has(language.slug)) {
    throw new Error('Every feed language must have a unique slug.');
  }
  slugs.add(language.slug);

  for (const period of periods) {
    const feedPath = language.feeds?.[period];
    if (
      typeof feedPath !== 'string' ||
      feedPath.length === 0 ||
      feedPath.startsWith('/') ||
      feedPath.split('/').includes('..')
    ) {
      throw new Error(`Invalid ${period} feed path for ${language.slug}.`);
    }
  }
}

const output = [
  '// Generated from the feed artifact. Do not edit this file by hand.',
  "import type { FeedManifest } from '../feed-manifest';",
  '',
  `export const feedManifest: FeedManifest = ${JSON.stringify(input, null, 2)};`,
  ''
].join('\n');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
