import fs from 'node:fs';
import path from 'node:path';

const [publicRootArgument, outputPathArgument] = process.argv.slice(2);
const publicRoot = path.resolve(publicRootArgument ?? 'website/public');
const outputPath = path.resolve(
  outputPathArgument ?? 'website/src/lib/generated/feed-entry-counts.ts',
);
const allowEmpty = process.argv.includes('--allow-empty');

if (!fs.existsSync(publicRoot)) {
  throw new Error(`Website public directory is missing: ${publicRoot}`);
}

function findXMLFiles(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) return findXMLFiles(entryPath);
    return entry.isFile() && entry.name.endsWith('.xml') ? [entryPath] : [];
  });
}

const entryCounts = Object.fromEntries(
  findXMLFiles(publicRoot)
    .sort()
    .map((filePath) => {
      const relativePath = path.relative(publicRoot, filePath).split(path.sep).join('/');
      const xml = fs.readFileSync(filePath, 'utf8');
      const count = xml.match(/<item(?:\s[^>]*)?>/g)?.length ?? 0;
      return [relativePath, count];
    }),
);

if (Object.keys(entryCounts).length === 0 && !allowEmpty) {
  throw new Error(`No RSS XML files found in: ${publicRoot}`);
}

const output = [
  '// Generated from the feed artifacts. Do not edit this file by hand.',
  "import type { FeedEntryCounts } from '../feed-manifest';",
  '',
  `export const feedEntryCounts: FeedEntryCounts = ${JSON.stringify(entryCounts, null, 2)};`,
  '',
].join('\n');

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output);
